GAMES = [
    # PRAGMATICPLAY
    {"name": "Sweet Bonanza", "provider": "PRAGMATICPLAY"},
    {"name": "Starlight Princess", "provider": "PRAGMATICPLAY"},
    {"name": "Gates of Olympus", "provider": "PRAGMATICPLAY"},
    {"name": "Sugar Rush", "provider": "PRAGMATICPLAY"},
    {"name": "Wild West Gold", "provider": "PRAGMATICPLAY"},
    {"name": "Joker's Jewels", "provider": "PRAGMATICPLAY"},
    {"name": "The Dog House", "provider": "PRAGMATICPLAY"},
    {"name": "Bonanza Gold", "provider": "PRAGMATICPLAY"},
    {"name": "Fruit Party", "provider": "PRAGMATICPLAY"},
    {"name": "Fruit Party 2", "provider": "PRAGMATICPLAY"},
    {"name": "Madame Destiny Megaways", "provider": "PRAGMATICPLAY"},
    {"name": "Great Rhino Megaways", "provider": "PRAGMATICPLAY"},
    {"name": "Aztec Gems", "provider": "PRAGMATICPLAY"},
    {"name": "Aztec Gems Deluxe", "provider": "PRAGMATICPLAY"},
    {"name": "Big Bass Bonanza", "provider": "PRAGMATICPLAY"},
    {"name": "Bigger Bass Bonanza", "provider": "PRAGMATICPLAY"},
    {"name": "Big Bass Splash", "provider": "PRAGMATICPLAY"},
    {"name": "John Hunter and the Tomb of the Scarab Queen", "provider": "PRAGMATICPLAY"},
    {"name": "John Hunter and the Book of Tut", "provider": "PRAGMATICPLAY"},
    {"name": "Wild Wild Riches", "provider": "PRAGMATICPLAY"},
    {"name": "5 Lions Gold", "provider": "PRAGMATICPLAY"},
    {"name": "5 Lions Megaways", "provider": "PRAGMATICPLAY"},
    {"name": "Mustang Gold", "provider": "PRAGMATICPLAY"},
    {"name": "Hot Fiesta", "provider": "PRAGMATICPLAY"},
    {"name": "Pyramid Bonanza", "provider": "PRAGMATICPLAY"},
    {"name": "Christmas Carol Megaways", "provider": "PRAGMATICPLAY"},
    {"name": "Zombie Carnival", "provider": "PRAGMATICPLAY"},
    {"name": "Fire Strike 2", "provider": "PRAGMATICPLAY"},
    {"name": "Floating Dragon", "provider": "PRAGMATICPLAY"},
    {"name": "Power of Thor Megaways", "provider": "PRAGMATICPLAY"},
    {"name": "The Hand of Midas", "provider": "PRAGMATICPLAY"},
    {"name": "Chilli Heat", "provider": "PRAGMATICPLAY"},
    {"name": "Cash Bonanza", "provider": "PRAGMATICPLAY"},
    {"name": "Buffalo King Megaways", "provider": "PRAGMATICPLAY"},
    {"name": "Spartan King", "provider": "PRAGMATICPLAY"},
    {"name": "Fire Hot 20", "provider": "PRAGMATICPLAY"},
    {"name": "Fire Hot 100", "provider": "PRAGMATICPLAY"},
    {"name": "Queenie", "provider": "PRAGMATICPLAY"},
    {"name": "Down the Rails", "provider": "PRAGMATICPLAY"},

    # PGSOFT
    {"name": "Mahjong Ways", "provider": "PGSOFT"},
    {"name": "Mahjong Ways 2", "provider": "PGSOFT"},
    {"name": "Lucky Neko", "provider": "PGSOFT"},
    {"name": "Wild Bandito", "provider": "PGSOFT"},
    {"name": "Queen of Bounty", "provider": "PGSOFT"},
    {"name": "Treasures of Aztec", "provider": "PGSOFT"},
    {"name": "Phoenix Rises", "provider": "PGSOFT"},
    {"name": "Egypt's Book Mystery", "provider": "PGSOFT"},
    {"name": "Crypto Gold", "provider": "PGSOFT"},
    {"name": "Candy Burst", "provider": "PGSOFT"},
    {"name": "Dragon Hatch", "provider": "PGSOFT"},
    {"name": "Caishen Wins", "provider": "PGSOFT"},
    {"name": "Double Fortune", "provider": "PGSOFT"},
    {"name": "Galactic Gems", "provider": "PGSOFT"},
    {"name": "The Great Icescape", "provider": "PGSOFT"},
    {"name": "Opera Dynasty", "provider": "PGSOFT"},
    {"name": "Bikini Paradise", "provider": "PGSOFT"},
    {"name": "Heist Stakes", "provider": "PGSOFT"},
    {"name": "Symbols of Egypt", "provider": "PGSOFT"},
    {"name": "Jurassic Kingdom", "provider": "PGSOFT"},
    {"name": "Fortune Tiger", "provider": "PGSOFT"},
    {"name": "Fortune Ox", "provider": "PGSOFT"},
    {"name": "Fortune Mouse", "provider": "PGSOFT"},
    {"name": "Rise of Apollo", "provider": "PGSOFT"},
    {"name": "Leprechaun Riches", "provider": "PGSOFT"},
    {"name": "Dreams of Macau", "provider": "PGSOFT"},
    {"name": "Legend of Hou Yi", "provider": "PGSOFT"},
    {"name": "Piggy Gold", "provider": "PGSOFT"},
    {"name": "Jungle Delight", "provider": "PGSOFT"},
    {"name": "Wizdom Wonders", "provider": "PGSOFT"},
    {"name": "Gem Saviour", "provider": "PGSOFT"},
    {"name": "Ways of the Qilin", "provider": "PGSOFT"},
    {"name": "Butterfly Blossom", "provider": "PGSOFT"},
    {"name": "Destiny of Sun and Moon", "provider": "PGSOFT"},
    {"name": "Legend of Perseus", "provider": "PGSOFT"},

    # HABANERO
    {"name": "Hot Hot Fruit", "provider": "HABANERO"},
    {"name": "Koi Gate", "provider": "HABANERO"},
    {"name": "Bikinin Island", "provider": "HABANERO"},
    {"name": "Fire Rooster", "provider": "HABANERO"},
    {"name": "Dragon's Throne", "provider": "HABANERO"},
    {"name": "Presto!", "provider": "HABANERO"},
    {"name": "Four Divine Beasts", "provider": "HABANERO"},
    {"name": "Wealth Inn", "provider": "HABANERO"},
    {"name": "Lucky Lucky", "provider": "HABANERO"},
    {"name": "5 Lucky Lions", "provider": "HABANERO"},
    {"name": "Fa Cai Shen Deluxe", "provider": "HABANERO"},
    {"name": "London Hunter", "provider": "HABANERO"},
    {"name": "Jump!", "provider": "HABANERO"},
    {"name": "Orbs of Atlantis", "provider": "HABANERO"},
    {"name": "Return to the Feature", "provider": "HABANERO"},
    {"name": "Totem Towers", "provider": "HABANERO"},
    {"name": "Happy Ape", "provider": "HABANERO"},

    # IDNSLOT
    {"name": "Joker's Treasure", "provider": "IDNSLOT"},
    {"name": "Myth of Phoenix", "provider": "IDNSLOT"},
    {"name": "Jungle King", "provider": "IDNSLOT"},
    {"name": "Legend of the Dragon", "provider": "IDNSLOT"},
    {"name": "Fruits Frenzy", "provider": "IDNSLOT"},
    {"name": "Ice Breaker", "provider": "IDNSLOT"},
    {"name": "Candy Pop", "provider": "IDNSLOT"},
    {"name": "88 Fortune", "provider": "IDNSLOT"},
    {"name": "Golden Panther", "provider": "IDNSLOT"},
    {"name": "Fruits Fiesta", "provider": "IDNSLOT"},
    {"name": "Super Color", "provider": "IDNSLOT"},
    {"name": "Apes Rampage", "provider": "IDNSLOT"},
    {"name": "Penguin Quest", "provider": "IDNSLOT"},
    {"name": "Cai Shen Dao", "provider": "IDNSLOT"},
    {"name": "Ocean Ruler", "provider": "IDNSLOT"},

    # NOLIMITCITY
    {"name": "San Quentin xWays", "provider": "NOLIMITCITY"},
    {"name": "Mental", "provider": "NOLIMITCITY"},
    {"name": "Tombstone RIP", "provider": "NOLIMITCITY"},
    {"name": "Deadwood", "provider": "NOLIMITCITY"},
    {"name": "Fire in the Hole xBomb", "provider": "NOLIMITCITY"},
    {"name": "The Rave", "provider": "NOLIMITCITY"},
    {"name": "Road Rage", "provider": "NOLIMITCITY"},
    {"name": "Misery Mining", "provider": "NOLIMITCITY"},
    {"name": "Das xBoot", "provider": "NOLIMITCITY"},
    {"name": "True Grit Redemption", "provider": "NOLIMITCITY"},
    {"name": "Dragon Tribe", "provider": "NOLIMITCITY"},
    {"name": "Book of Shadows", "provider": "NOLIMITCITY"},
    {"name": "Warrior Graveyard xNudge", "provider": "NOLIMITCITY"},
    {"name": "Karen Maneater", "provider": "NOLIMITCITY"},
    {"name": "Bushido Ways xNudge", "provider": "NOLIMITCITY"}
]
